runtime: java
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "17"

env_variables:
  SPRING_PROFILES_ACTIVE: 'dev1'


