# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: F2

env_variables:
  SPRING_PROFILES_ACTIVE: 'prod'
  DB_URL: $DB_URL
  DB_USERNAME: $DB_USERNAME
  DB_PASSWORD: $DB_PASSWORD
