runtime: java17
instance_class: F2

env_variables:
  SPRING_PROFILES_ACTIVE: 'prod'
  DB_URL: '${{ secrets.DB_URL }}'
  DB_USERNAME: '${{ secrets.DB_USERNAME }}'
  DB_PASSWORD: '${{ secrets.DB_PASSWORD }}'
